#!/bin/sh
IPDIR=../../misc
rm -rf work
rm -f SUCCESS
vlib work
vlog -sv -cover bcesft tb3.sv ../*sv avst.sv ${IPDIR}/endianness.sv ${IPDIR}/crc32.sv ${IPDIR}/sync.sv
vsim -sv_seed random -L altera_mf -L lpm -c -do "run -all" -coverage tb_st_if_3
