#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 *
 * Created from SOPC Builder system 'base_hps' in
 * file 'base_hps.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 *
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'rl_encoder_if', class 'rl_encoder_if'
 * The macros are prefixed with 'RL_ENCODER_IF_'.
 * The prefix is the slave descriptor.
 */
#define RL_ENCODER_IF_COMPONENT_TYPE rl_encoder_if
#define RL_ENCODER_IF_COMPONENT_NAME rl_encoder_if
#define RL_ENCODER_IF_BASE 0x0
#define RL_ENCODER_IF_SPAN 16
#define RL_ENCODER_IF_END 0xf

/*
 * Macros for device 'sw_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'SW_PIO_'.
 * The prefix is the slave descriptor.
 */
#define SW_PIO_COMPONENT_TYPE altera_avalon_pio
#define SW_PIO_COMPONENT_NAME sw_pio
#define SW_PIO_BASE 0x0
#define SW_PIO_SPAN 16
#define SW_PIO_END 0xf
#define SW_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define SW_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SW_PIO_CAPTURE 0
#define SW_PIO_DATA_WIDTH 4
#define SW_PIO_DO_TEST_BENCH_WIRING 0
#define SW_PIO_DRIVEN_SIM_VALUE 0
#define SW_PIO_EDGE_TYPE NONE
#define SW_PIO_FREQ 100000000
#define SW_PIO_HAS_IN 1
#define SW_PIO_HAS_OUT 0
#define SW_PIO_HAS_TRI 0
#define SW_PIO_IRQ_TYPE NONE
#define SW_PIO_RESET_VALUE 0

/*
 * Macros for device 'pb_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'PB_PIO_'.
 * The prefix is the slave descriptor.
 */
#define PB_PIO_COMPONENT_TYPE altera_avalon_pio
#define PB_PIO_COMPONENT_NAME pb_pio
#define PB_PIO_BASE 0x10
#define PB_PIO_SPAN 16
#define PB_PIO_END 0x1f
#define PB_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define PB_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PB_PIO_CAPTURE 0
#define PB_PIO_DATA_WIDTH 2
#define PB_PIO_DO_TEST_BENCH_WIRING 0
#define PB_PIO_DRIVEN_SIM_VALUE 0
#define PB_PIO_EDGE_TYPE NONE
#define PB_PIO_FREQ 100000000
#define PB_PIO_HAS_IN 1
#define PB_PIO_HAS_OUT 0
#define PB_PIO_HAS_TRI 0
#define PB_PIO_IRQ_TYPE NONE
#define PB_PIO_RESET_VALUE 0

/*
 * Macros for device 'led_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'LED_PIO_'.
 * The prefix is the slave descriptor.
 */
#define LED_PIO_COMPONENT_TYPE altera_avalon_pio
#define LED_PIO_COMPONENT_NAME led_pio
#define LED_PIO_BASE 0x20
#define LED_PIO_SPAN 16
#define LED_PIO_END 0x2f
#define LED_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define LED_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LED_PIO_CAPTURE 0
#define LED_PIO_DATA_WIDTH 8
#define LED_PIO_DO_TEST_BENCH_WIRING 0
#define LED_PIO_DRIVEN_SIM_VALUE 0
#define LED_PIO_EDGE_TYPE NONE
#define LED_PIO_FREQ 100000000
#define LED_PIO_HAS_IN 0
#define LED_PIO_HAS_OUT 1
#define LED_PIO_HAS_TRI 0
#define LED_PIO_IRQ_TYPE NONE
#define LED_PIO_RESET_VALUE 85

/*
 * Macros for device 'sysid', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_COMPONENT_NAME sysid
#define SYSID_BASE 0x30
#define SYSID_SPAN 8
#define SYSID_END 0x37
#define SYSID_ID 3451985116
#define SYSID_TIMESTAMP 1776415104

/*
 * Macros for device 'sysid_qsys_0', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_0_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_0_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_0_COMPONENT_NAME sysid_qsys_0
#define SYSID_QSYS_0_BASE 0x38
#define SYSID_QSYS_0_SPAN 8
#define SYSID_QSYS_0_END 0x3f
#define SYSID_QSYS_0_ID 35
#define SYSID_QSYS_0_TIMESTAMP 1776415104

/*
 * Macros for device 'fifo_ts_pps_out', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_TS_PPS_OUT_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_TS_PPS_OUT_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_TS_PPS_OUT_COMPONENT_NAME fifo_ts_pps
#define FIFO_TS_PPS_OUT_BASE 0x40
#define FIFO_TS_PPS_OUT_SPAN 8
#define FIFO_TS_PPS_OUT_END 0x47
#define FIFO_TS_PPS_OUT_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_TS_PPS_OUT_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_TS_PPS_OUT_BITS_PER_SYMBOL 32
#define FIFO_TS_PPS_OUT_CHANNEL_WIDTH 0
#define FIFO_TS_PPS_OUT_ERROR_WIDTH 0
#define FIFO_TS_PPS_OUT_FIFO_DEPTH 16
#define FIFO_TS_PPS_OUT_SINGLE_CLOCK_MODE 1
#define FIFO_TS_PPS_OUT_SYMBOLS_PER_BEAT 1
#define FIFO_TS_PPS_OUT_USE_AVALONMM_READ_SLAVE 1
#define FIFO_TS_PPS_OUT_USE_AVALONMM_WRITE_SLAVE 0
#define FIFO_TS_PPS_OUT_USE_AVALONST_SINK 1
#define FIFO_TS_PPS_OUT_USE_AVALONST_SOURCE 0
#define FIFO_TS_PPS_OUT_USE_BACKPRESSURE 1
#define FIFO_TS_PPS_OUT_USE_IRQ 0
#define FIFO_TS_PPS_OUT_USE_PACKET 0
#define FIFO_TS_PPS_OUT_USE_READ_CONTROL 0
#define FIFO_TS_PPS_OUT_USE_REGISTER 0
#define FIFO_TS_PPS_OUT_USE_WRITE_CONTROL 1

/*
 * Macros for device 'adc_ltc2308', class 'altera_up_avalon_adc'
 * The macros are prefixed with 'ADC_LTC2308_'.
 * The prefix is the slave descriptor.
 */
#define ADC_LTC2308_COMPONENT_TYPE altera_up_avalon_adc
#define ADC_LTC2308_COMPONENT_NAME adc_ltc2308
#define ADC_LTC2308_BASE 0x40
#define ADC_LTC2308_SPAN 32
#define ADC_LTC2308_END 0x5f

/*
 * Macros for device 'fifo_ts_pps_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_TS_PPS_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_TS_PPS_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_TS_PPS_IN_CSR_COMPONENT_NAME fifo_ts_pps
#define FIFO_TS_PPS_IN_CSR_BASE 0x60
#define FIFO_TS_PPS_IN_CSR_SPAN 32
#define FIFO_TS_PPS_IN_CSR_END 0x7f
#define FIFO_TS_PPS_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_TS_PPS_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_TS_PPS_IN_CSR_BITS_PER_SYMBOL 32
#define FIFO_TS_PPS_IN_CSR_CHANNEL_WIDTH 0
#define FIFO_TS_PPS_IN_CSR_ERROR_WIDTH 0
#define FIFO_TS_PPS_IN_CSR_FIFO_DEPTH 16
#define FIFO_TS_PPS_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_TS_PPS_IN_CSR_SYMBOLS_PER_BEAT 1
#define FIFO_TS_PPS_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_TS_PPS_IN_CSR_USE_AVALONMM_WRITE_SLAVE 0
#define FIFO_TS_PPS_IN_CSR_USE_AVALONST_SINK 1
#define FIFO_TS_PPS_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_TS_PPS_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_TS_PPS_IN_CSR_USE_IRQ 0
#define FIFO_TS_PPS_IN_CSR_USE_PACKET 0
#define FIFO_TS_PPS_IN_CSR_USE_READ_CONTROL 0
#define FIFO_TS_PPS_IN_CSR_USE_REGISTER 0
#define FIFO_TS_PPS_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'pio_trig_int', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_TRIG_INT_'.
 * The prefix is the slave descriptor.
 */
#define PIO_TRIG_INT_COMPONENT_TYPE altera_avalon_pio
#define PIO_TRIG_INT_COMPONENT_NAME pio_trig_int
#define PIO_TRIG_INT_BASE 0x60
#define PIO_TRIG_INT_SPAN 32
#define PIO_TRIG_INT_END 0x7f
#define PIO_TRIG_INT_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_TRIG_INT_BIT_MODIFYING_OUTPUT_REGISTER 1
#define PIO_TRIG_INT_CAPTURE 0
#define PIO_TRIG_INT_DATA_WIDTH 11
#define PIO_TRIG_INT_DO_TEST_BENCH_WIRING 0
#define PIO_TRIG_INT_DRIVEN_SIM_VALUE 0
#define PIO_TRIG_INT_EDGE_TYPE NONE
#define PIO_TRIG_INT_FREQ 100000000
#define PIO_TRIG_INT_HAS_IN 0
#define PIO_TRIG_INT_HAS_OUT 1
#define PIO_TRIG_INT_HAS_TRI 0
#define PIO_TRIG_INT_IRQ_TYPE NONE
#define PIO_TRIG_INT_RESET_VALUE 0

/*
 * Macros for device 'fifo_ts_sigA_out', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_TS_SIGA_OUT_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_TS_SIGA_OUT_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_TS_SIGA_OUT_COMPONENT_NAME fifo_ts_sigA
#define FIFO_TS_SIGA_OUT_BASE 0x80
#define FIFO_TS_SIGA_OUT_SPAN 8
#define FIFO_TS_SIGA_OUT_END 0x87
#define FIFO_TS_SIGA_OUT_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_TS_SIGA_OUT_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_TS_SIGA_OUT_BITS_PER_SYMBOL 32
#define FIFO_TS_SIGA_OUT_CHANNEL_WIDTH 0
#define FIFO_TS_SIGA_OUT_ERROR_WIDTH 0
#define FIFO_TS_SIGA_OUT_FIFO_DEPTH 16
#define FIFO_TS_SIGA_OUT_SINGLE_CLOCK_MODE 1
#define FIFO_TS_SIGA_OUT_SYMBOLS_PER_BEAT 1
#define FIFO_TS_SIGA_OUT_USE_AVALONMM_READ_SLAVE 1
#define FIFO_TS_SIGA_OUT_USE_AVALONMM_WRITE_SLAVE 0
#define FIFO_TS_SIGA_OUT_USE_AVALONST_SINK 1
#define FIFO_TS_SIGA_OUT_USE_AVALONST_SOURCE 0
#define FIFO_TS_SIGA_OUT_USE_BACKPRESSURE 1
#define FIFO_TS_SIGA_OUT_USE_IRQ 0
#define FIFO_TS_SIGA_OUT_USE_PACKET 0
#define FIFO_TS_SIGA_OUT_USE_READ_CONTROL 0
#define FIFO_TS_SIGA_OUT_USE_REGISTER 0
#define FIFO_TS_SIGA_OUT_USE_WRITE_CONTROL 1

/*
 * Macros for device 'pio_trig_monitor', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_TRIG_MONITOR_'.
 * The prefix is the slave descriptor.
 */
#define PIO_TRIG_MONITOR_COMPONENT_TYPE altera_avalon_pio
#define PIO_TRIG_MONITOR_COMPONENT_NAME pio_trig_monitor
#define PIO_TRIG_MONITOR_BASE 0x80
#define PIO_TRIG_MONITOR_SPAN 32
#define PIO_TRIG_MONITOR_END 0x9f
#define PIO_TRIG_MONITOR_BIT_CLEARING_EDGE_REGISTER 1
#define PIO_TRIG_MONITOR_BIT_MODIFYING_OUTPUT_REGISTER 1
#define PIO_TRIG_MONITOR_CAPTURE 0
#define PIO_TRIG_MONITOR_DATA_WIDTH 32
#define PIO_TRIG_MONITOR_DO_TEST_BENCH_WIRING 0
#define PIO_TRIG_MONITOR_DRIVEN_SIM_VALUE 0
#define PIO_TRIG_MONITOR_EDGE_TYPE NONE
#define PIO_TRIG_MONITOR_FREQ 100000000
#define PIO_TRIG_MONITOR_HAS_IN 1
#define PIO_TRIG_MONITOR_HAS_OUT 0
#define PIO_TRIG_MONITOR_HAS_TRI 0
#define PIO_TRIG_MONITOR_IRQ_TYPE NONE
#define PIO_TRIG_MONITOR_RESET_VALUE 0

/*
 * Macros for device 'pio_aux', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_AUX_'.
 * The prefix is the slave descriptor.
 */
#define PIO_AUX_COMPONENT_TYPE altera_avalon_pio
#define PIO_AUX_COMPONENT_NAME pio_aux
#define PIO_AUX_BASE 0xa0
#define PIO_AUX_SPAN 32
#define PIO_AUX_END 0xbf
#define PIO_AUX_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_AUX_BIT_MODIFYING_OUTPUT_REGISTER 1
#define PIO_AUX_CAPTURE 0
#define PIO_AUX_DATA_WIDTH 8
#define PIO_AUX_DO_TEST_BENCH_WIRING 0
#define PIO_AUX_DRIVEN_SIM_VALUE 0
#define PIO_AUX_EDGE_TYPE NONE
#define PIO_AUX_FREQ 100000000
#define PIO_AUX_HAS_IN 1
#define PIO_AUX_HAS_OUT 1
#define PIO_AUX_HAS_TRI 0
#define PIO_AUX_IRQ_TYPE NONE
#define PIO_AUX_RESET_VALUE 0

/*
 * Macros for device 'freq_meter_0', class 'freq_meter'
 * The macros are prefixed with 'FREQ_METER_0_'.
 * The prefix is the slave descriptor.
 */
#define FREQ_METER_0_COMPONENT_TYPE freq_meter
#define FREQ_METER_0_COMPONENT_NAME freq_meter_0
#define FREQ_METER_0_BASE 0xc0
#define FREQ_METER_0_SPAN 64
#define FREQ_METER_0_END 0xff

/*
 * Macros for device 'pio_cfg', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_CFG_'.
 * The prefix is the slave descriptor.
 */
#define PIO_CFG_COMPONENT_TYPE altera_avalon_pio
#define PIO_CFG_COMPONENT_NAME pio_cfg
#define PIO_CFG_BASE 0xc0
#define PIO_CFG_SPAN 32
#define PIO_CFG_END 0xdf
#define PIO_CFG_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_CFG_BIT_MODIFYING_OUTPUT_REGISTER 1
#define PIO_CFG_CAPTURE 0
#define PIO_CFG_DATA_WIDTH 13
#define PIO_CFG_DO_TEST_BENCH_WIRING 0
#define PIO_CFG_DRIVEN_SIM_VALUE 0
#define PIO_CFG_EDGE_TYPE NONE
#define PIO_CFG_FREQ 100000000
#define PIO_CFG_HAS_IN 0
#define PIO_CFG_HAS_OUT 1
#define PIO_CFG_HAS_TRI 0
#define PIO_CFG_IRQ_TYPE NONE
#define PIO_CFG_RESET_VALUE 0

/*
 * Macros for device 'fifo_ts_sigA_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_TS_SIGA_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_TS_SIGA_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_TS_SIGA_IN_CSR_COMPONENT_NAME fifo_ts_sigA
#define FIFO_TS_SIGA_IN_CSR_BASE 0x100
#define FIFO_TS_SIGA_IN_CSR_SPAN 32
#define FIFO_TS_SIGA_IN_CSR_END 0x11f
#define FIFO_TS_SIGA_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_TS_SIGA_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_TS_SIGA_IN_CSR_BITS_PER_SYMBOL 32
#define FIFO_TS_SIGA_IN_CSR_CHANNEL_WIDTH 0
#define FIFO_TS_SIGA_IN_CSR_ERROR_WIDTH 0
#define FIFO_TS_SIGA_IN_CSR_FIFO_DEPTH 16
#define FIFO_TS_SIGA_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_TS_SIGA_IN_CSR_SYMBOLS_PER_BEAT 1
#define FIFO_TS_SIGA_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_TS_SIGA_IN_CSR_USE_AVALONMM_WRITE_SLAVE 0
#define FIFO_TS_SIGA_IN_CSR_USE_AVALONST_SINK 1
#define FIFO_TS_SIGA_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_TS_SIGA_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_TS_SIGA_IN_CSR_USE_IRQ 0
#define FIFO_TS_SIGA_IN_CSR_USE_PACKET 0
#define FIFO_TS_SIGA_IN_CSR_USE_READ_CONTROL 0
#define FIFO_TS_SIGA_IN_CSR_USE_REGISTER 0
#define FIFO_TS_SIGA_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'ts_core_pps', class 'ts_core'
 * The macros are prefixed with 'TS_CORE_PPS_'.
 * The prefix is the slave descriptor.
 */
#define TS_CORE_PPS_COMPONENT_TYPE ts_core
#define TS_CORE_PPS_COMPONENT_NAME ts_core_pps
#define TS_CORE_PPS_BASE 0x120
#define TS_CORE_PPS_SPAN 16
#define TS_CORE_PPS_END 0x12f

/*
 * Macros for device 'pio_elapsed', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_ELAPSED_'.
 * The prefix is the slave descriptor.
 */
#define PIO_ELAPSED_COMPONENT_TYPE altera_avalon_pio
#define PIO_ELAPSED_COMPONENT_NAME pio_elapsed
#define PIO_ELAPSED_BASE 0x1b0
#define PIO_ELAPSED_SPAN 16
#define PIO_ELAPSED_END 0x1bf
#define PIO_ELAPSED_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_ELAPSED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_ELAPSED_CAPTURE 0
#define PIO_ELAPSED_DATA_WIDTH 32
#define PIO_ELAPSED_DO_TEST_BENCH_WIRING 0
#define PIO_ELAPSED_DRIVEN_SIM_VALUE 0
#define PIO_ELAPSED_EDGE_TYPE NONE
#define PIO_ELAPSED_FREQ 100000000
#define PIO_ELAPSED_HAS_IN 1
#define PIO_ELAPSED_HAS_OUT 0
#define PIO_ELAPSED_HAS_TRI 0
#define PIO_ELAPSED_IRQ_TYPE NONE
#define PIO_ELAPSED_RESET_VALUE 0

/*
 * Macros for device 'sysid_qsys_1', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_1_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_1_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_1_COMPONENT_NAME sysid_qsys_1
#define SYSID_QSYS_1_BASE 0x200
#define SYSID_QSYS_1_SPAN 8
#define SYSID_QSYS_1_END 0x207
#define SYSID_QSYS_1_ID 4
#define SYSID_QSYS_1_TIMESTAMP 1776415104

/*
 * Macros for device 'pll_reconfig_int_clk', class 'altera_pll_reconfig'
 * The macros are prefixed with 'PLL_RECONFIG_INT_CLK_'.
 * The prefix is the slave descriptor.
 */
#define PLL_RECONFIG_INT_CLK_COMPONENT_TYPE altera_pll_reconfig
#define PLL_RECONFIG_INT_CLK_COMPONENT_NAME pll_reconfig_int_clk
#define PLL_RECONFIG_INT_CLK_BASE 0x400
#define PLL_RECONFIG_INT_CLK_SPAN 256
#define PLL_RECONFIG_INT_CLK_END 0x4ff

/*
 * Macros for device 'pll_reconfig_core_clk', class 'altera_pll_reconfig'
 * The macros are prefixed with 'PLL_RECONFIG_CORE_CLK_'.
 * The prefix is the slave descriptor.
 */
#define PLL_RECONFIG_CORE_CLK_COMPONENT_TYPE altera_pll_reconfig
#define PLL_RECONFIG_CORE_CLK_COMPONENT_NAME pll_reconfig_core_clk
#define PLL_RECONFIG_CORE_CLK_BASE 0x700
#define PLL_RECONFIG_CORE_CLK_SPAN 256
#define PLL_RECONFIG_CORE_CLK_END 0x7ff

/*
 * Macros for device 'msgdma_1_csr', class 'altera_msgdma'
 * The macros are prefixed with 'MSGDMA_1_CSR_'.
 * The prefix is the slave descriptor.
 */
#define MSGDMA_1_CSR_COMPONENT_TYPE altera_msgdma
#define MSGDMA_1_CSR_COMPONENT_NAME msgdma_1
#define MSGDMA_1_CSR_BASE 0x1000
#define MSGDMA_1_CSR_SPAN 32
#define MSGDMA_1_CSR_END 0x101f
#define MSGDMA_1_CSR_IRQ 1
#define MSGDMA_1_CSR_BURST_ENABLE 1
#define MSGDMA_1_CSR_BURST_WRAPPING_SUPPORT 1
#define MSGDMA_1_CSR_CHANNEL_ENABLE 0
#define MSGDMA_1_CSR_CHANNEL_ENABLE_DERIVED 0
#define MSGDMA_1_CSR_CHANNEL_WIDTH 8
#define MSGDMA_1_CSR_DATA_FIFO_DEPTH 1024
#define MSGDMA_1_CSR_DATA_WIDTH 32
#define MSGDMA_1_CSR_DESCRIPTOR_FIFO_DEPTH 32
#define MSGDMA_1_CSR_DMA_MODE 1
#define MSGDMA_1_CSR_ENHANCED_FEATURES 0
#define MSGDMA_1_CSR_ERROR_ENABLE 0
#define MSGDMA_1_CSR_ERROR_ENABLE_DERIVED 0
#define MSGDMA_1_CSR_ERROR_WIDTH 8
#define MSGDMA_1_CSR_MAX_BURST_COUNT 256
#define MSGDMA_1_CSR_MAX_BYTE 536870912
#define MSGDMA_1_CSR_MAX_STRIDE 1
#define MSGDMA_1_CSR_PACKET_ENABLE 0
#define MSGDMA_1_CSR_PACKET_ENABLE_DERIVED 0
#define MSGDMA_1_CSR_PREFETCHER_ENABLE 0
#define MSGDMA_1_CSR_PROGRAMMABLE_BURST_ENABLE 0
#define MSGDMA_1_CSR_RESPONSE_PORT 2
#define MSGDMA_1_CSR_STRIDE_ENABLE 0
#define MSGDMA_1_CSR_STRIDE_ENABLE_DERIVED 0
#define MSGDMA_1_CSR_TRANSFER_TYPE Full Word Accesses Only

/*
 * Macros for device 'st_mux_1', class 'st_mux'
 * The macros are prefixed with 'ST_MUX_1_'.
 * The prefix is the slave descriptor.
 */
#define ST_MUX_1_COMPONENT_TYPE st_mux
#define ST_MUX_1_COMPONENT_NAME st_mux_1
#define ST_MUX_1_BASE 0x1100
#define ST_MUX_1_SPAN 32
#define ST_MUX_1_END 0x111f

/*
 * Macros for device 'msgdma_1_descriptor_slave', class 'altera_msgdma'
 * The macros are prefixed with 'MSGDMA_1_DESCRIPTOR_SLAVE_'.
 * The prefix is the slave descriptor.
 */
#define MSGDMA_1_DESCRIPTOR_SLAVE_COMPONENT_TYPE altera_msgdma
#define MSGDMA_1_DESCRIPTOR_SLAVE_COMPONENT_NAME msgdma_1
#define MSGDMA_1_DESCRIPTOR_SLAVE_BASE 0x2000
#define MSGDMA_1_DESCRIPTOR_SLAVE_SPAN 16
#define MSGDMA_1_DESCRIPTOR_SLAVE_END 0x200f
#define MSGDMA_1_DESCRIPTOR_SLAVE_BURST_ENABLE 1
#define MSGDMA_1_DESCRIPTOR_SLAVE_BURST_WRAPPING_SUPPORT 1
#define MSGDMA_1_DESCRIPTOR_SLAVE_CHANNEL_ENABLE 0
#define MSGDMA_1_DESCRIPTOR_SLAVE_CHANNEL_ENABLE_DERIVED 0
#define MSGDMA_1_DESCRIPTOR_SLAVE_CHANNEL_WIDTH 8
#define MSGDMA_1_DESCRIPTOR_SLAVE_DATA_FIFO_DEPTH 1024
#define MSGDMA_1_DESCRIPTOR_SLAVE_DATA_WIDTH 32
#define MSGDMA_1_DESCRIPTOR_SLAVE_DESCRIPTOR_FIFO_DEPTH 32
#define MSGDMA_1_DESCRIPTOR_SLAVE_DMA_MODE 1
#define MSGDMA_1_DESCRIPTOR_SLAVE_ENHANCED_FEATURES 0
#define MSGDMA_1_DESCRIPTOR_SLAVE_ERROR_ENABLE 0
#define MSGDMA_1_DESCRIPTOR_SLAVE_ERROR_ENABLE_DERIVED 0
#define MSGDMA_1_DESCRIPTOR_SLAVE_ERROR_WIDTH 8
#define MSGDMA_1_DESCRIPTOR_SLAVE_MAX_BURST_COUNT 256
#define MSGDMA_1_DESCRIPTOR_SLAVE_MAX_BYTE 536870912
#define MSGDMA_1_DESCRIPTOR_SLAVE_MAX_STRIDE 1
#define MSGDMA_1_DESCRIPTOR_SLAVE_PACKET_ENABLE 0
#define MSGDMA_1_DESCRIPTOR_SLAVE_PACKET_ENABLE_DERIVED 0
#define MSGDMA_1_DESCRIPTOR_SLAVE_PREFETCHER_ENABLE 0
#define MSGDMA_1_DESCRIPTOR_SLAVE_PROGRAMMABLE_BURST_ENABLE 0
#define MSGDMA_1_DESCRIPTOR_SLAVE_RESPONSE_PORT 2
#define MSGDMA_1_DESCRIPTOR_SLAVE_STRIDE_ENABLE 0
#define MSGDMA_1_DESCRIPTOR_SLAVE_STRIDE_ENABLE_DERIVED 0
#define MSGDMA_1_DESCRIPTOR_SLAVE_TRANSFER_TYPE Full Word Accesses Only

/*
 * Macros for device 'fifo_1_in', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_1_IN_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_1_IN_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_1_IN_COMPONENT_NAME fifo_1
#define FIFO_1_IN_BASE 0x4000
#define FIFO_1_IN_SPAN 8
#define FIFO_1_IN_END 0x4007
#define FIFO_1_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_1_IN_BITS_PER_SYMBOL 8
#define FIFO_1_IN_CHANNEL_WIDTH 0
#define FIFO_1_IN_ERROR_WIDTH 0
#define FIFO_1_IN_FIFO_DEPTH 1024
#define FIFO_1_IN_SINGLE_CLOCK_MODE 1
#define FIFO_1_IN_SYMBOLS_PER_BEAT 4
#define FIFO_1_IN_USE_AVALONMM_READ_SLAVE 0
#define FIFO_1_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1_IN_USE_AVALONST_SINK 0
#define FIFO_1_IN_USE_AVALONST_SOURCE 1
#define FIFO_1_IN_USE_BACKPRESSURE 1
#define FIFO_1_IN_USE_IRQ 0
#define FIFO_1_IN_USE_PACKET 0
#define FIFO_1_IN_USE_READ_CONTROL 0
#define FIFO_1_IN_USE_REGISTER 0
#define FIFO_1_IN_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_2_in', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_2_IN_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_2_IN_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_2_IN_COMPONENT_NAME fifo_2
#define FIFO_2_IN_BASE 0x4100
#define FIFO_2_IN_SPAN 8
#define FIFO_2_IN_END 0x4107
#define FIFO_2_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_2_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_2_IN_BITS_PER_SYMBOL 8
#define FIFO_2_IN_CHANNEL_WIDTH 0
#define FIFO_2_IN_ERROR_WIDTH 0
#define FIFO_2_IN_FIFO_DEPTH 1024
#define FIFO_2_IN_SINGLE_CLOCK_MODE 1
#define FIFO_2_IN_SYMBOLS_PER_BEAT 4
#define FIFO_2_IN_USE_AVALONMM_READ_SLAVE 0
#define FIFO_2_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_2_IN_USE_AVALONST_SINK 0
#define FIFO_2_IN_USE_AVALONST_SOURCE 1
#define FIFO_2_IN_USE_BACKPRESSURE 1
#define FIFO_2_IN_USE_IRQ 0
#define FIFO_2_IN_USE_PACKET 0
#define FIFO_2_IN_USE_READ_CONTROL 0
#define FIFO_2_IN_USE_REGISTER 0
#define FIFO_2_IN_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_3_in', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_3_IN_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_3_IN_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_3_IN_COMPONENT_NAME fifo_3
#define FIFO_3_IN_BASE 0x4200
#define FIFO_3_IN_SPAN 8
#define FIFO_3_IN_END 0x4207
#define FIFO_3_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_3_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_3_IN_BITS_PER_SYMBOL 8
#define FIFO_3_IN_CHANNEL_WIDTH 0
#define FIFO_3_IN_ERROR_WIDTH 0
#define FIFO_3_IN_FIFO_DEPTH 1024
#define FIFO_3_IN_SINGLE_CLOCK_MODE 1
#define FIFO_3_IN_SYMBOLS_PER_BEAT 4
#define FIFO_3_IN_USE_AVALONMM_READ_SLAVE 0
#define FIFO_3_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_3_IN_USE_AVALONST_SINK 0
#define FIFO_3_IN_USE_AVALONST_SOURCE 1
#define FIFO_3_IN_USE_BACKPRESSURE 1
#define FIFO_3_IN_USE_IRQ 0
#define FIFO_3_IN_USE_PACKET 0
#define FIFO_3_IN_USE_READ_CONTROL 0
#define FIFO_3_IN_USE_REGISTER 0
#define FIFO_3_IN_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_4_in', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_4_IN_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_4_IN_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_4_IN_COMPONENT_NAME fifo_4
#define FIFO_4_IN_BASE 0x4300
#define FIFO_4_IN_SPAN 8
#define FIFO_4_IN_END 0x4307
#define FIFO_4_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_4_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_4_IN_BITS_PER_SYMBOL 8
#define FIFO_4_IN_CHANNEL_WIDTH 0
#define FIFO_4_IN_ERROR_WIDTH 0
#define FIFO_4_IN_FIFO_DEPTH 1024
#define FIFO_4_IN_SINGLE_CLOCK_MODE 1
#define FIFO_4_IN_SYMBOLS_PER_BEAT 4
#define FIFO_4_IN_USE_AVALONMM_READ_SLAVE 0
#define FIFO_4_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_4_IN_USE_AVALONST_SINK 0
#define FIFO_4_IN_USE_AVALONST_SOURCE 1
#define FIFO_4_IN_USE_BACKPRESSURE 1
#define FIFO_4_IN_USE_IRQ 0
#define FIFO_4_IN_USE_PACKET 0
#define FIFO_4_IN_USE_READ_CONTROL 0
#define FIFO_4_IN_USE_REGISTER 0
#define FIFO_4_IN_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_1_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_1_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_1_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_1_IN_CSR_COMPONENT_NAME fifo_1
#define FIFO_1_IN_CSR_BASE 0x4400
#define FIFO_1_IN_CSR_SPAN 32
#define FIFO_1_IN_CSR_END 0x441f
#define FIFO_1_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_1_IN_CSR_BITS_PER_SYMBOL 8
#define FIFO_1_IN_CSR_CHANNEL_WIDTH 0
#define FIFO_1_IN_CSR_ERROR_WIDTH 0
#define FIFO_1_IN_CSR_FIFO_DEPTH 1024
#define FIFO_1_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_1_IN_CSR_SYMBOLS_PER_BEAT 4
#define FIFO_1_IN_CSR_USE_AVALONMM_READ_SLAVE 0
#define FIFO_1_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_1_IN_CSR_USE_AVALONST_SOURCE 1
#define FIFO_1_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_1_IN_CSR_USE_IRQ 0
#define FIFO_1_IN_CSR_USE_PACKET 0
#define FIFO_1_IN_CSR_USE_READ_CONTROL 0
#define FIFO_1_IN_CSR_USE_REGISTER 0
#define FIFO_1_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_2_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_2_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_2_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_2_IN_CSR_COMPONENT_NAME fifo_2
#define FIFO_2_IN_CSR_BASE 0x4500
#define FIFO_2_IN_CSR_SPAN 32
#define FIFO_2_IN_CSR_END 0x451f
#define FIFO_2_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_2_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_2_IN_CSR_BITS_PER_SYMBOL 8
#define FIFO_2_IN_CSR_CHANNEL_WIDTH 0
#define FIFO_2_IN_CSR_ERROR_WIDTH 0
#define FIFO_2_IN_CSR_FIFO_DEPTH 1024
#define FIFO_2_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_2_IN_CSR_SYMBOLS_PER_BEAT 4
#define FIFO_2_IN_CSR_USE_AVALONMM_READ_SLAVE 0
#define FIFO_2_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_2_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_2_IN_CSR_USE_AVALONST_SOURCE 1
#define FIFO_2_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_2_IN_CSR_USE_IRQ 0
#define FIFO_2_IN_CSR_USE_PACKET 0
#define FIFO_2_IN_CSR_USE_READ_CONTROL 0
#define FIFO_2_IN_CSR_USE_REGISTER 0
#define FIFO_2_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_3_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_3_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_3_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_3_IN_CSR_COMPONENT_NAME fifo_3
#define FIFO_3_IN_CSR_BASE 0x4600
#define FIFO_3_IN_CSR_SPAN 32
#define FIFO_3_IN_CSR_END 0x461f
#define FIFO_3_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_3_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_3_IN_CSR_BITS_PER_SYMBOL 8
#define FIFO_3_IN_CSR_CHANNEL_WIDTH 0
#define FIFO_3_IN_CSR_ERROR_WIDTH 0
#define FIFO_3_IN_CSR_FIFO_DEPTH 1024
#define FIFO_3_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_3_IN_CSR_SYMBOLS_PER_BEAT 4
#define FIFO_3_IN_CSR_USE_AVALONMM_READ_SLAVE 0
#define FIFO_3_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_3_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_3_IN_CSR_USE_AVALONST_SOURCE 1
#define FIFO_3_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_3_IN_CSR_USE_IRQ 0
#define FIFO_3_IN_CSR_USE_PACKET 0
#define FIFO_3_IN_CSR_USE_READ_CONTROL 0
#define FIFO_3_IN_CSR_USE_REGISTER 0
#define FIFO_3_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_4_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_4_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_4_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_4_IN_CSR_COMPONENT_NAME fifo_4
#define FIFO_4_IN_CSR_BASE 0x4700
#define FIFO_4_IN_CSR_SPAN 32
#define FIFO_4_IN_CSR_END 0x471f
#define FIFO_4_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_4_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_4_IN_CSR_BITS_PER_SYMBOL 8
#define FIFO_4_IN_CSR_CHANNEL_WIDTH 0
#define FIFO_4_IN_CSR_ERROR_WIDTH 0
#define FIFO_4_IN_CSR_FIFO_DEPTH 1024
#define FIFO_4_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_4_IN_CSR_SYMBOLS_PER_BEAT 4
#define FIFO_4_IN_CSR_USE_AVALONMM_READ_SLAVE 0
#define FIFO_4_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_4_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_4_IN_CSR_USE_AVALONST_SOURCE 1
#define FIFO_4_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_4_IN_CSR_USE_IRQ 0
#define FIFO_4_IN_CSR_USE_PACKET 0
#define FIFO_4_IN_CSR_USE_READ_CONTROL 0
#define FIFO_4_IN_CSR_USE_REGISTER 0
#define FIFO_4_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'sysid_h2f', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_H2F_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_H2F_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_H2F_COMPONENT_NAME sysid_h2f
#define SYSID_H2F_BASE 0x5000
#define SYSID_H2F_SPAN 8
#define SYSID_H2F_END 0x5007
#define SYSID_H2F_ID 305441741
#define SYSID_H2F_TIMESTAMP 1776415104

/*
 * Macros for device 'st_interface_1', class 'st_interface'
 * The macros are prefixed with 'ST_INTERFACE_1_'.
 * The prefix is the slave descriptor.
 */
#define ST_INTERFACE_1_COMPONENT_TYPE st_interface
#define ST_INTERFACE_1_COMPONENT_NAME st_interface_1
#define ST_INTERFACE_1_BASE 0x6000
#define ST_INTERFACE_1_SPAN 128
#define ST_INTERFACE_1_END 0x607f

/*
 * Macros for device 'st_interface_2', class 'st_interface'
 * The macros are prefixed with 'ST_INTERFACE_2_'.
 * The prefix is the slave descriptor.
 */
#define ST_INTERFACE_2_COMPONENT_TYPE st_interface
#define ST_INTERFACE_2_COMPONENT_NAME st_interface_2
#define ST_INTERFACE_2_BASE 0x6100
#define ST_INTERFACE_2_SPAN 128
#define ST_INTERFACE_2_END 0x617f

/*
 * Macros for device 'st_interface_3', class 'st_interface'
 * The macros are prefixed with 'ST_INTERFACE_3_'.
 * The prefix is the slave descriptor.
 */
#define ST_INTERFACE_3_COMPONENT_TYPE st_interface
#define ST_INTERFACE_3_COMPONENT_NAME st_interface_3
#define ST_INTERFACE_3_BASE 0x6200
#define ST_INTERFACE_3_SPAN 128
#define ST_INTERFACE_3_END 0x627f

/*
 * Macros for device 'st_interface_4', class 'st_interface'
 * The macros are prefixed with 'ST_INTERFACE_4_'.
 * The prefix is the slave descriptor.
 */
#define ST_INTERFACE_4_COMPONENT_TYPE st_interface
#define ST_INTERFACE_4_COMPONENT_NAME st_interface_4
#define ST_INTERFACE_4_BASE 0x6300
#define ST_INTERFACE_4_SPAN 128
#define ST_INTERFACE_4_END 0x637f

/*
 * Macros for device 'combiner_trig', class 'combiner_trig'
 * The macros are prefixed with 'COMBINER_TRIG_'.
 * The prefix is the slave descriptor.
 */
#define COMBINER_TRIG_COMPONENT_TYPE combiner_trig
#define COMBINER_TRIG_COMPONENT_NAME combiner_trig
#define COMBINER_TRIG_BASE 0x7000
#define COMBINER_TRIG_SPAN 64
#define COMBINER_TRIG_END 0x703f

/*
 * Macros for device 'combiner_qout', class 'combiner'
 * The macros are prefixed with 'COMBINER_QOUT_'.
 * The prefix is the slave descriptor.
 */
#define COMBINER_QOUT_COMPONENT_TYPE combiner
#define COMBINER_QOUT_COMPONENT_NAME combiner_qout
#define COMBINER_QOUT_BASE 0x7100
#define COMBINER_QOUT_SPAN 64
#define COMBINER_QOUT_END 0x713f

/*
 * Macros for device 'fifo_rl_out', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_RL_OUT_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_RL_OUT_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_RL_OUT_COMPONENT_NAME fifo_rl
#define FIFO_RL_OUT_BASE 0x8000
#define FIFO_RL_OUT_SPAN 8
#define FIFO_RL_OUT_END 0x8007
#define FIFO_RL_OUT_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_RL_OUT_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_RL_OUT_BITS_PER_SYMBOL 32
#define FIFO_RL_OUT_CHANNEL_WIDTH 0
#define FIFO_RL_OUT_ERROR_WIDTH 0
#define FIFO_RL_OUT_FIFO_DEPTH 1024
#define FIFO_RL_OUT_SINGLE_CLOCK_MODE 1
#define FIFO_RL_OUT_SYMBOLS_PER_BEAT 1
#define FIFO_RL_OUT_USE_AVALONMM_READ_SLAVE 1
#define FIFO_RL_OUT_USE_AVALONMM_WRITE_SLAVE 0
#define FIFO_RL_OUT_USE_AVALONST_SINK 1
#define FIFO_RL_OUT_USE_AVALONST_SOURCE 0
#define FIFO_RL_OUT_USE_BACKPRESSURE 1
#define FIFO_RL_OUT_USE_IRQ 0
#define FIFO_RL_OUT_USE_PACKET 0
#define FIFO_RL_OUT_USE_READ_CONTROL 0
#define FIFO_RL_OUT_USE_REGISTER 0
#define FIFO_RL_OUT_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_rl_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_RL_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_RL_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_RL_IN_CSR_COMPONENT_NAME fifo_rl
#define FIFO_RL_IN_CSR_BASE 0x8100
#define FIFO_RL_IN_CSR_SPAN 32
#define FIFO_RL_IN_CSR_END 0x811f
#define FIFO_RL_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_RL_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_RL_IN_CSR_BITS_PER_SYMBOL 32
#define FIFO_RL_IN_CSR_CHANNEL_WIDTH 0
#define FIFO_RL_IN_CSR_ERROR_WIDTH 0
#define FIFO_RL_IN_CSR_FIFO_DEPTH 1024
#define FIFO_RL_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_RL_IN_CSR_SYMBOLS_PER_BEAT 1
#define FIFO_RL_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_RL_IN_CSR_USE_AVALONMM_WRITE_SLAVE 0
#define FIFO_RL_IN_CSR_USE_AVALONST_SINK 1
#define FIFO_RL_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_RL_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_RL_IN_CSR_USE_IRQ 0
#define FIFO_RL_IN_CSR_USE_PACKET 0
#define FIFO_RL_IN_CSR_USE_READ_CONTROL 0
#define FIFO_RL_IN_CSR_USE_REGISTER 0
#define FIFO_RL_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'counter_q', class 'counter'
 * The macros are prefixed with 'COUNTER_Q_'.
 * The prefix is the slave descriptor.
 */
#define COUNTER_Q_COMPONENT_TYPE counter
#define COUNTER_Q_COMPONENT_NAME counter_q
#define COUNTER_Q_BASE 0xa000
#define COUNTER_Q_SPAN 64
#define COUNTER_Q_END 0xa03f


#endif /* _ALTERA_HPS_0_H_ */
