# TCL File Generated by Component Editor 21.1
# Sat Nov 01 20:12:39 CET 2025
# DO NOT MODIFY


# 
# counter "counter" v1.0
# Rok Zitko 2025.11.01.20:12:39
# Measure basic statistics on digital lines
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module counter
# 
set_module_property DESCRIPTION "Measure basic statistics on digital lines"
set_module_property NAME counter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP rzhw
set_module_property AUTHOR "Rok Zitko"
set_module_property DISPLAY_NAME counter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL counter_if
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file autocorrelation.sv SYSTEM_VERILOG PATH ip/counter/autocorrelation.sv
add_fileset_file basic_counter.sv SYSTEM_VERILOG PATH ip/counter/basic_counter.sv
add_fileset_file crosscorrelation.sv SYSTEM_VERILOG PATH ip/counter/crosscorrelation.sv
add_fileset_file mux32to1.sv SYSTEM_VERILOG PATH ip/counter/mux32to1.sv
add_fileset_file mux32to2.sv SYSTEM_VERILOG PATH ip/counter/mux32to2.sv
add_fileset_file packet_stats.sv SYSTEM_VERILOG PATH ip/counter/packet_stats.sv
add_fileset_file runs_counter.sv SYSTEM_VERILOG PATH ip/counter/runs_counter.sv
add_fileset_file seq_counter.sv SYSTEM_VERILOG PATH ip/counter/seq_counter.sv
add_fileset_file time_counter.sv SYSTEM_VERILOG PATH ip/counter/time_counter.sv
add_fileset_file cdc.v VERILOG PATH ip/counter/cdc.v
add_fileset_file counter_if.sv SYSTEM_VERILOG PATH ip/counter/counter_if.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter width_data INTEGER 32
set_parameter_property width_data DEFAULT_VALUE 32
set_parameter_property width_data DISPLAY_NAME width_data
set_parameter_property width_data TYPE INTEGER
set_parameter_property width_data UNITS None
set_parameter_property width_data HDL_PARAMETER true
add_parameter width_bus INTEGER 32
set_parameter_property width_bus DEFAULT_VALUE 32
set_parameter_property width_bus DISPLAY_NAME width_bus
set_parameter_property width_bus TYPE INTEGER
set_parameter_property width_bus UNITS None
set_parameter_property width_bus HDL_PARAMETER true
add_parameter width_addr INTEGER 8
set_parameter_property width_addr DEFAULT_VALUE 8
set_parameter_property width_addr DISPLAY_NAME width_addr
set_parameter_property width_addr TYPE INTEGER
set_parameter_property width_addr UNITS None
set_parameter_property width_addr HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_address address Input 4
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_readdata readdata Output 32
add_interface_port s0 avs_s0_writedata writedata Input 32
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end d data Input 32
add_interface_port conduit_end d_clk clock Input 1
add_interface_port conduit_end d_valid valid Input 1

