# TCL File Generated by Component Editor 18.1
# Fri Jun 12 18:15:28 CEST 2020
# DO NOT MODIFY


#
# st_interface "st_interface" v1.0
#  2020.06.12.18:15:28
#
#

#
# request TCL package from ACDS 16.1
#
package require -exact qsys 16.1


#
# module st_interface
#
set_module_property DESCRIPTION "Parallel data streamer"
set_module_property NAME st_interface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP rzhw
set_module_property AUTHOR "Rok Zitko"
set_module_property DISPLAY_NAME st_interface
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL st_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS true
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file st_interface.sv SYSTEMVERILOG PATH ip/streamer/st_interface.sv TOP_LEVEL_FILE
add_fileset_file endianness.sv SYSTEMVERILOG PATH ip/misc/endianness.sv
add_fileset_file crc32.sv SYSTEMVERILOG PATH ip/misc/crc32.sv
add_fileset_file sync.sv SYSTEMVERILOG PATH ip/misc/sync.sv
add_fileset_file cdc.sv SYSTEMVERILOG PATH ip/misc/cdc.sv
add_fileset_file input_fifo.sv SYSTEMVERILOG PATH ip/streamer/input_fifo.sv
add_fileset_file preprocessor.sv SYSTEMVERILOG PATH ip/streamer/preprocessor.sv
add_fileset_file level_to_pulse.sv SYSTEMVERILOG PATH ip/streamer/level_to_pulse.sv
add_fileset_file output_fifo.sv SYSTEMVERILOG PATH ip/streamer/output_fifo.sv
add_fileset_file rl_decoder.sv SYSTEMVERILOG PATH ip/streamer/rl_decoder.sv
add_fileset_file streamer.sv SYSTEMVERILOG PATH ip/streamer/streamer.sv
add_fileset_file and_trigger.sv SYSTEMVERILOG PATH ip/streamer/and_trigger.sv
add_fileset_file chain_trigger.sv SYSTEMVERILOG PATH ip/streamer/chain_trigger.sv
add_fileset_file prng.sv SYSTEMVERILOG PATH ip/streamer/prng.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL st_interface
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS true
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file st_interface.sv SYSTEMVERILOG PATH ip/streamer/st_interface.sv
add_fileset_file endianness.sv SYSTEMVERILOG PATH ip/misc/endianness.sv
add_fileset_file crc32.sv SYSTEMVERILOG PATH ip/misc/crc32.sv
add_fileset_file sync.sv SYSTEMVERILOG PATH ip/misc/sync.sv
add_fileset_file cdc.sv SYSTEMVERILOG PATH ip/misc/cdc.sv
add_fileset_file input_fifo.sv SYSTEMVERILOG PATH ip/streamer/input_fifo.sv
add_fileset_file preprocessor.sv SYSTEMVERILOG PATH ip/streamer/preprocessor.sv
add_fileset_file level_to_pulse.sv SYSTEMVERILOG PATH ip/streamer/level_to_pulse.sv
add_fileset_file output_fifo.sv SYSTEMVERILOG PATH ip/streamer/output_fifo.sv
add_fileset_file rl_decoder.sv SYSTEMVERILOG PATH ip/streamer/rl_decoder.sv
add_fileset_file streamer.sv SYSTEMVERILOG PATH ip/streamer/streamer.sv
add_fileset_file and_trigger.sv SYSTEMVERILOG PATH ip/streamer/and_trigger.sv
add_fileset_file chain_trigger.sv SYSTEMVERILOG PATH ip/streamer/chain_trigger.sv
add_fileset_file prng.sv SYSTEMVERILOG PATH ip/streamer/prng.sv


#
# parameters
#


#
# module assignments
#
set_module_assignment embeddedsw.dts.compatible dev,st_interface
set_module_assignment embeddedsw.dts.group leds,st_if
set_module_assignment embeddedsw.dts.vendor dsa


#
# display items
#


#
# connection point clock
#
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


#
# connection point reset
#
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


#
# connection point avalon_streaming_sink_0
#
add_interface avalon_streaming_sink_0 avalon_streaming end
set_interface_property avalon_streaming_sink_0 associatedClock clock
set_interface_property avalon_streaming_sink_0 associatedReset reset
set_interface_property avalon_streaming_sink_0 dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink_0 errorDescriptor ""
set_interface_property avalon_streaming_sink_0 firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink_0 maxChannel 1
set_interface_property avalon_streaming_sink_0 readyLatency 0
set_interface_property avalon_streaming_sink_0 ENABLED true
set_interface_property avalon_streaming_sink_0 EXPORT_OF ""
set_interface_property avalon_streaming_sink_0 PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink_0 asi_data data Input 96
add_interface_port avalon_streaming_sink_0 asi_valid valid Input 1
add_interface_port avalon_streaming_sink_0 asi_channel channel Input 1
add_interface_port avalon_streaming_sink_0 asi_ready ready Output 1

#
# connection point s0
#
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_address address Input 5
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_readdata readdata Output 32
add_interface_port s0 avs_s0_writedata writedata Input 32
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


#
# connection point conduit_end
#
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end streamer_clk streamer_clk Input 1
add_interface_port conduit_end qout qout Output 32
add_interface_port conduit_end qout_valid qout_valid Output 1
add_interface_port conduit_end qout_strobe qout_strobe Output 1
add_interface_port conduit_end strobe_enable strobe_enable Output 1
add_interface_port conduit_end done done Output 1
add_interface_port conduit_end buffer_error buffer_error Output 1
add_interface_port conduit_end trigger_in trigger_in Input 8
add_interface_port conduit_end trigger_enable_ext trigger_enable Input 1
add_interface_port conduit_end trigger_reset_ext trigger_reset Input 1
add_interface_port conduit_end trigger_force_ext trigger_force Input 1
add_interface_port conduit_end trigger_armed trigger_armed Output 1
add_interface_port conduit_end trigger_activated trigger_activated Output 1
add_interface_port conduit_end gate_in gate_in Input 1
