# TCL File Generated by Component Editor 21.1
# Tue Nov 04 20:15:13 CET 2025
# DO NOT MODIFY


#
# ts_core "ts_core" v1.0
# Rok Zitko 2025.11.04.20:15:13
# Timestamping core, output using Avalon ST
#

#
# request TCL package from ACDS 16.1
#
package require -exact qsys 16.1


#
# module ts_core
#
set_module_property DESCRIPTION "Timestamping core, output using Avalon ST"
set_module_property NAME ts_core
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP rzhw
set_module_property AUTHOR "Rok Zitko"
set_module_property DISPLAY_NAME ts_core
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ts_core
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ts_core.sv SYSTEM_VERILOG PATH ip/ts_core/ts_core.sv TOP_LEVEL_FILE


#
# parameters
#
add_parameter CTR_W INTEGER 64
set_parameter_property CTR_W DEFAULT_VALUE 64
set_parameter_property CTR_W DISPLAY_NAME CTR_W
set_parameter_property CTR_W TYPE INTEGER
set_parameter_property CTR_W UNITS None
set_parameter_property CTR_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CTR_W HDL_PARAMETER true


#
# display items
#


#
# connection point clock
#
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


#
# connection point reset
#
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


#
# connection point avalon_streaming_source_0
#
add_interface avalon_streaming_source_0 avalon_streaming start
set_interface_property avalon_streaming_source_0 associatedClock clock
set_interface_property avalon_streaming_source_0 associatedReset reset
set_interface_property avalon_streaming_source_0 dataBitsPerSymbol 32
set_interface_property avalon_streaming_source_0 errorDescriptor ""
set_interface_property avalon_streaming_source_0 firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source_0 maxChannel 0
set_interface_property avalon_streaming_source_0 readyLatency 0
set_interface_property avalon_streaming_source_0 ENABLED true
set_interface_property avalon_streaming_source_0 EXPORT_OF ""
set_interface_property avalon_streaming_source_0 PORT_NAME_MAP ""
set_interface_property avalon_streaming_source_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source_0 aso_valid valid Output 1
add_interface_port avalon_streaming_source_0 aso_data data Output "((CTR_W-1)) - (0) + 1"
add_interface_port avalon_streaming_source_0 aso_ready ready Input 1


#
# connection point avalon_streaming_source_1
#
add_interface avalon_streaming_source_1 avalon_streaming start
set_interface_property avalon_streaming_source_1 associatedClock clock
set_interface_property avalon_streaming_source_1 associatedReset reset
set_interface_property avalon_streaming_source_1 dataBitsPerSymbol 32
set_interface_property avalon_streaming_source_1 errorDescriptor ""
set_interface_property avalon_streaming_source_1 firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source_1 maxChannel 0
set_interface_property avalon_streaming_source_1 readyLatency 0
set_interface_property avalon_streaming_source_1 ENABLED true
set_interface_property avalon_streaming_source_1 EXPORT_OF ""
set_interface_property avalon_streaming_source_1 PORT_NAME_MAP ""
set_interface_property avalon_streaming_source_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source_1 asoA_valid valid Output 1
add_interface_port avalon_streaming_source_1 asoA_data data Output "((CTR_W-1)) - (0) + 1"
add_interface_port avalon_streaming_source_1 asoA_ready ready Input 1


#
# connection point conduit_end
#
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end sig sig Input 1
add_interface_port conduit_end sigA sigA Input 1
