#!/bin/bash
# Tests that depend on FIFO buffer being sufficiently large.
set -e
source "$(dirname "$0")/../defs.sh"

# Max size that still fits the input FIFO buffers
pptest 8 -c 120000 -v 629 -check -dump-converted
