#!/usr/bin/env perl

# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Rok Zitko

use strict;
use warnings;
use File::Path qw(make_path);

sub system_failure {
    my ($status) = @_;
    if ($status == -1) {
        return (127, "failed to execute: $!");
    }
    if ($status & 127) {
        my $signal = $status & 127;
        my $core = ($status & 128) ? " with core dump" : "";
        return (128 + $signal, "killed by signal $signal$core");
    }
    my $rc = $status >> 8;
    return $rc == 0 ? (0, "") : ($rc, "exited with code $rc");
}

my $save_report_files = 1;

while (@ARGV) {
    my $arg = shift @ARGV;
    if ($arg eq '-no-report-files') {
        $save_report_files = 0;
    } else {
        die "Unknown argument: $arg\n";
    }
}

# This will generate a lot of output.
# Use a RAM-based storage mount point, not the SD card!
my $logdir = "/var/volatile/pulsepins-test-logs";
make_path($logdir) unless -d $logdir;
(-d $logdir && -w $logdir) or die "$logdir not writable.";

unlink "$logdir/report";
unlink glob("$logdir/report.*") if $save_report_files; # clean up first!

sub get_pptest_report_header {
    my $output = `pptest 0 2>&1`;
    my $version = "Version unavailable";
    my $bitstream_timestamp = "Bitstream timestamp: unavailable";
    for my $line (split /\n/, $output) {
        if ($line =~ /^Version /) {
            $version = $line;
        }
        if ($line =~ /^Bitstream timestamp: /) {
            $bitstream_timestamp = $line;
        }
    }
    return "# run_all_tests_forever report\n# $version\n# $bitstream_timestamp\n\n";
}

my $report_header = get_pptest_report_header();

my $summary_report = "$logdir/report";
open(my $O, ">", $summary_report) or die "Could not write $summary_report: $!";
select((select($O), $| = 1)[0]);
print $O $report_header;

for (my $i = 1 ; ; $i++) {
    if ($save_report_files) {
        open(my $R, ">$logdir/report.run_$i") or die "Could not write $logdir/report.run_$i: $!";
        print $R $report_header;
        close($R);
    }
    my $run_report = "$logdir/report.run_$i";
    my $status = $save_report_files
        ? system("bash", "-o", "pipefail", "-c", 'run_all_tests 2>&1 | tee -a "$1"', "run_all_tests_forever", $run_report)
        : system("run_all_tests");
    my ($rc, $failure) = system_failure($status);
    if ($rc != 0) {
        my $message = "FAILED run $i: $failure";
        print "$message\n";
        print $O "$message\n";
        exit($rc);
    }
    my $time = scalar localtime;
    print $O "$i -- $time\n"; # log successful runs
}
