#!/usr/bin/env perl

# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Rok Zitko

use strict;
use warnings;
use File::Basename;

my $skip_re;

while (@ARGV) {
    my $arg = shift @ARGV;
    if ($arg eq '-skip') {
        defined($skip_re = shift @ARGV)
          or die "-skip requires a regular expression argument\n";
    } else {
        die "Unknown argument: $arg\n";
    }
}

# This will generate a lot of output.
# Use a RAM-based storage mount point, not the SD card!
my $logdir = "/var/volatile";
(-d $logdir && -w $logdir) or die "$logdir not writable.";

my $cntr = 0;

chdir("/home/root/tests") or die;

for my $t (glob "./test*") {
  next unless -f $t && -x $t;
  next if $t =~ /-inf/;   # skip if "-inf" in filename (infinite duration tests)
  next if $t =~ /-pll/;   # skip if "-pll" in filename, these are best run manually
  next if defined($skip_re) && $t =~ /$skip_re/;  # user-specified skips

  my $test = basename($t);
  print "\nRunning $t [$test]...\n";
  system("bash", "-o", "pipefail", "-c", "$t 2>&1 | tee $logdir/report.$test");
  my $rc = $? >> 8;   # extract exit code
  print "rc=$rc\n" if $rc != 0;
  exit(1) if $rc != 0;   # stop if not zero
}

print "SUCCESS\n";
