#!/bin/bash
ppscpi &
sleep .1
RESPONSE=$(nc localhost 5025 2>/dev/null <<'EOF'
*IDN?
CHECK ON
SEQ d 10 0xff d 5 0x00 d 2 0b0101 f
STREAM
TERMINATE
EOF
)

RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
RST="\033[0m"

echo "Reponse: $RESPONSE"
if [[ $RESPONSE == *"SUCCESS"* ]]; then
  echo -e "${GREEN}SUCCESS${RST}"
  exit 0
else
  echo -e "${RED}FAILURE${RST}"
  exit 1
fi
