#!/bin/sh
# Tests for clock synthesis using PLL
source defs.sh

pptest 3 -c 1_000 -v 1_000 -check -core_pll 100M
pptest 3 -c 1_000 -v 1_000 -check -core_pll 75M
pptest 3 -c 1_000 -v 1_000 -check -core_pll 50M
pptest 3 -c 1_000 -v 1_000 -check -core_pll 25M
pptest 3 -c 1_000 -v 1_000 -check -core_pll 20M
pptest 3 -c 1_000 -v 1_000 -check -core_pll 10M
pptest 3 -c 1_000 -v 1_000 -check -core_pll 1M
