#!/bin/bash
source defs.sh
pptest 15 -check -trig -c 10_000 -cycles 1 -v 4
pptest 15 -check -trig -c 10_000 -cycles 2 -v 4
pptest 15 -check -trig -c 10_000 -cycles 3 -v 4
pptest 15 -check -trig -c 10_000 -cycles 10 -v 4

pptest 15 -check -trig -c 1 -cycles 10 -v 4
pptest 15 -check -trig -c 10 -cycles 10 -v 4
pptest 15 -check -trig -c 100 -cycles 10 -v 4
pptest 15 -check -trig -c 1_000 -cycles 10 -v 4
pptest 15 -check -trig -c 10_000 -cycles 10 -v 4

pptest 15 -check -trig -c 10_000 -cycles 10 -v 1
pptest 15 -check -trig -c 10_000 -cycles 10 -v 10
