#!/bin/bash
ppserver &
sleep .1
RESPONSE=$(echo "TEST1" | nc localhost 5025 2>/dev/null)
sleep .1
echo "TERMINATE" | nc localhost 5025

RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
RST="\033[0m"

echo "Reponse: $RESPONSE"
if [[ $RESPONSE == *"SUCCESS"* ]]; then
  echo -e "${GREEN}SUCCESS${RST}"
  exit 0
else
  echo -e "${RED}FAILURE${RST}"
  exit 1
fi
