#!/bin/bash
source defs.sh
pptest 2 -c 10_000_000 -v 42 -check
pptest 2 -c 1_000_000 -v 42 -check
pptest 2 -c 100_000 -v 42 -check
pptest 2 -c 10_000 -v 42 -check
pptest 2 -c 1_000 -v 42 -check
pptest 2 -c 100 -v 42 -check
pptest 2 -c 10 -v 42 -check
pptest 2 -c 1 -v 42 -check
pptest 2 -c 0 -v 42 -check
# -dump-converted

time pptest 2 -c 100_000_000 -v 42 -check
time pptest 2 -c 1_000_000_000 -v 42 -check
time pptest 2 -c 0xffffffff -v 42 -check
