#!/bin/bash
set -e
source "$(dirname "$0")/defs.sh"
ppts -nr 5
# Timeout -> non-zero RC, hence || :
ppts -nr 10 -timeout 3.0 -selA 0 -sigA || :
ppts -nr 10 -timeout 10.0 -selA 7 -sigA -ignore_ts_overflow
ppts -nr 10 -timeout 10.0 -selA 6 -sigA
ppts -nr 10 -timeout 10.0 -selA 5 -sigA
ppts -nr 10 -timeout 10.0 -selA 4 -sigA
