#!/bin/sh
rm -f tb1
iverilog -g2012 -DDO_SUM2 -DCOUNTER_CC -o tb1 ../counter_if.sv ../basic_counter.sv ../runs_counter.sv ../seq_counter.sv ../autocorrelation.sv \
  ../packet_stats.sv ../mux32to1.sv ../mux32to2.sv ../crosscorrelation.sv ../time_counter.sv ../cdc.v tb1.sv
