# See /intelFPGA_lite/21.1/questa_fse/modelsim.ini

; Treat implicit nets and undeclared nettypes as errors
set MsgConfig vlog-2889 -error
set MsgConfig vlog-2892 -error

; Default vlog options for every compile
VlogDefaultOptions = -sv -lint -pedanticerrors
